name: Refresh Offer Index
on:
  schedule:
    - cron: "*/30 * * * *" # every 30 minutes
  workflow_dispatch: # allow manual trigger

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Call refresh endpoint
        run: |
          curl -sS -X POST "$SITE_URL/api/admin/refresh-index" \
            -H "x-cron-token: $CRON_TOKEN" \
            -H "Content-Type: application/json"
        env:
          SITE_URL: ${{ secrets.SITE_URL }}
          CRON_TOKEN: ${{ secrets.CRON_TOKEN }}